- lib/client.js
- test/opentok-test.js
On 503, the library isn't throwing the right error otherwise.
> Throw server errors for 503

- package.json
which updates [ms](https://www.npmjs.com/package/ms) package ms@0.7.3 is vulnerable to a ReDoS attack: https://snyk.io/vuln/npm:ms:20170412
> Updating jsonwebtoken dependency

- sample/Archiving/public/js/host.js
- sample/Archiving/public/js/participant.js
Remove the info parameter from the connect callback. We don't need it anymore.
Make sure the archiving demo still works.
> Remove the info parameter from the connect callback

- README.md
- lib/opentok.js
- sample/Archiving/public/js/host.js
- sample/Archiving/public/js/participant.js
- sample/Archiving/views/host.ejs
- sample/Archiving/views/participant.ejs
- sample/HelloWorld/public/js/helloworld.js
- sample/HelloWorld/views/index.ejs
- sample/SipInterconnect/views/index.ejs
- Point users to the Client SDK on NPM in case that's what they're looking for.
- Update samples to use latest client SDK API and CDN URL
> Update JS samples and references to Client SDK

- lib/archiving.js
It adds the resolution field in the archive, so that we can enable clients to start composers with different resolutions. The supported till now are "1280x720" and "640x480".
I tested it by modifying the sample archiving app. Used the "tbdev" environment, where this feature is enabled.
OPENTOK-36017
> Add Composed Archiving resolution parameter on creation (OPENTOK-36017)

- lib/opentok.js
- test/opentok-test.js
Adds the ability to pass in the `from` field as a part of the `options` object for the `dial` method
Dial out and add `from` as a part of the options
#197
> add ability to pass from field for sip dial

- lib/opentok.js
"X-" prefix for custom headers no longer required
Correcting some docs.
Run jsdoc.
None.
> Correction to SIP docs

- lib/client.js
- test/opentok-test.js
The error message currently only contains [object Object], which make integration harder to debug.
This is a minor fix on the error messages.
A unit test was added to cover the `startBroadcast` case.
There is none.
> Fix error reporting on client for startBroadcast and setStreamClassLists

- lib/archiving.js
- package.json
- spec/opentok_spec.js
Insures that archiving options are respected for false attributes.
Increases verbosity of errors from archiving requests for better debugging.
Start archive in manual mode and make sure addStream options are respected in terms of audio/video components.
https://video-api.support.vonage.com/hc/en-us/requests/1990354
> Fix JS issues / increase error usefulness

- lib/archiving.js
- lib/broadcast.js
- lib/opentok.js
This updates `startArchive` to accept in the `multiArchiveTag` parameter.
```js
opentok.startArchive(
sessionId, 
{
name: 'My awesome session',
multiArchiveTag: 'tagging this session',
},
(err, archive) => {
if (err) {
console.err(err);
return;
}
console.log(archive);
);
```
[DEVX-6489](https://jira.vonage.com/browse/DEVX-6489)
> Added multiArchiveTag to startArchive

- lib/errors.js
- lib/opentok.js
- lib/render.js
Adding the render
```js 
opentok.listRenders({}, (err, renders) => {
if (err) {
console.log("There was an error")
console.log(err);
return;
}
console.log(renders);
})
opentok.getRender('<render id>', (err, render) => {
if (err) {
console.log("There was an error")
console.log(err);
return;
}
console.log(render);
})
opentok.startRender(
{
sessionId: sessionId,
token: token,
url: '<callback url>',
}, 
(err, render) => {
if (err) {
console.log("There was an error")
console.log(err);
return;
}
console.log(render);
}
)
opentok.stopRender('<render id>', (err, render) => {
if (err) {
console.log("There was an error")
console.log(err);
return;
}
console.log(render);
})
```
[DEVX-6495](https://jira.vonage.com/browse/DEVX-6495)
> Experience Composer API enhancements

- lib/client.js
- test/opentok-test.js
Changes `PATCH` requests to watch for a 204 status code instead of a 200 response code, per https://tokbox.com/developer/rest/#selecting-broadcast-streams
Try adding a stream to an existing broadcast
Came in via support
> fix: Patch requests to broadcasts now watch for 204 instead of 200

- lib/archiving.js
- lib/callbacks.js
- lib/moderation.js
- lib/signaling.js
1) Adding details of what when wrong when an `Unexpected response from OpenTok` occurred.
2) Fixing a bug where the method `unregisterCallback` would reject with a `400 - Bad Request` because the body was not null.
Steps:
1. create a callback using `registerCallback` 
2. then remove it using `unregisterCallback`
- https://github.com/opentok/opentok-node/issues/290
> fix: Bad request on callback deletion

- lib/opentok.js
- lib/render.js
Adding documentation for the e2ee parameter
> docs: e2ee added to create session

- lib/opentok.js
Adding new parameters for archive documentation in `createSession`
> docs: adding auto archive documentation

- .eslintrc
- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- .gitignore
- lib/archiving.js
- lib/callbacks.js
- lib/client.js
- lib/moderation.js
- lib/opentok.js
- lib/render.js
- lib/signaling.js
- package-lock.json
- package.json
- spec/opentok_spec.js
- test/callbacks-test.js
- test/opentok-test.js
This PR removes the 'requests' package, which has not been updated in over 6 years and has major security errors.
> fix: removing dependancy for node-requests

- lib/client.js
- package.json
- test/opentok-test.js
> fix: post encoding for client

- lib/client.js
- package-lock.json
- test/opentok-test.js
This is addressing cases where decoding of JSON responses where being done in the callback rather than after the request is made.
> fix: double decoding of json

- lib/client.js
- test/opentok-test.js
Fixing an issue when the API does not return the `items` when listing streams
> fix: map error when items is not defined for list streams

- lib/opentok.js
Adding the new "publisher-only" role for token generation
This will be tested with the JS client SDK
TBD, but trust me there will be JIRA tickets
> Added Publisher Only role

- lib/captions.js
- lib/errors.js
- lib/opentok.js
- test/opentok-test.js
This is adding support to start and stop captions
Start and stop captions for a stream
> feat: adding support for captions

- lib/archiving.js
- lib/opentok.js
- spec/opentok_spec.js
> Added maxbitrate to archives

- lib/generateJwt.js
- lib/opentok.js
- test/opentok-test.js
Changes the Node SDK to using JWTs for generating client-side tokens, with a fallback to T1 tokens if requested. The fallback _is not_ documented and should only be used if the user runs into issues and support ends up contacting engineering or devrel.
Build a token and try in the playground. There are automated tests with this change.
DEVX-8989
> Swapped to JWT tokens

- lib/broadcast.js
- lib/opentok.js
.... and other minor edits
Adding some missing docs and minor docs edits.
N/A
N/A
> Adding docs for generateT1Token option

- lib/opentok.js
- test/opentok-test.js
This PR adds a new flag in the websocket connect api, which enables/disables this feature for the user.
By enabling this flag, user should be able to send the data from the websocket server back in to the opentok session. Previously it was only in one direction.
https://jira.vonage.com/browse/VIDMC-1226
> feat: Add bidirectional flag in websocket connect [VIDMC-1226] 
