lib/opentok.js, test/opentok-test.js
fixes #76 
threw in a fix for #90, and clarified the code that fixed #77
=> rounds expire time

.eslintignore, .eslintrc, .gitignore, Gruntfile.js, lib/archiving.js, lib/client.js, lib/errors.js, lib/opentok.js, lib/session.js, lib/sipInterconnect.js, package.json, spec/opentok_spec.js, test/.eslintrc, test/helpers.js, test/opentok-test.js, test/session-test.js
Added eslint and started applying linting rules.
=> Adding linting

.github/pull_request_template.md, lib/client.js
See title, also adds PR template.
Set your system clock forward by 5 minutes and run ![run!](http://dreamatico.com/data_images/run/run-4.jpg)
... this code:
```js
'use strict';
const OpenTok = require('.');
const ot = new OpenTok('100', '19f149fdf697474f915f13de40e0ad53');
ot.createSession((err, session) => {
if (err) {
throw err;
}    
console.log(session);
});  
```
Without this change you get:
```
Error: Failed to createSession. Error: An authentication error occurred: (403) [object Object]
```
With this change you get:
```
Error: Failed to createSession. Error: An authentication error occurred: (403) {"code":-1,"message":"Issued time cannot be in the future."}
```
... and don't forget to turn sync back on for your system clock.
(If you're wondering how my system clock ended up in the …
=> Stringify response body in error messages

README.md, lib/opentok.js, package.json, test/opentok-test.js
See https://github.com/opentok/opentok-node/pull/152
=> Jeffswartz 2.6.0

lib/archiving.js, lib/callbacks.js, lib/client.js, lib/generateJwt.js, lib/moderation.js, lib/opentok.js, test/callbacks-test.js, test/moderation-test.js
Callback and moderation APIs were merged with deprecated URL/auth
=> Update callbacks/moderation API not to use deprecated URL/auth

lib/errors.js
Simple fix for exports missing in errors.js
grunt tests executed, should be fine.
#167
=> Fix minor issue with exports in errors

README.md
Updating the README file 
N/A
N/A
=> remove working with callbacks section

sample/Archiving/package.json, sample/HelloWorld/package.json, sample/SipInterconnect/package.json
=> updating ejs dependencies

.gitignore, README.md, lib/archiving.js, lib/callbacks.js, lib/opentok.js, lib/sipInterconnect.js, sample/Archiving/public/js/host.js, sample/Archiving/public/js/participant.js, sample/HelloWorld/public/js/helloworld.js, sample/HelloWorld/views/index.ejs, sample/SipInterconnect/README.md, sample/SipInterconnect/app.js, sample/SipInterconnect/package.json, sample/SipInterconnect/views/index.ejs
Fixing some documentation and sample code issues.
For the samples, you can follow the README instructions in the samples subdirectories.
=> Docs samples corrections

.eslintignore, .eslintrc, lib/archiving.js, lib/callbacks.js, lib/client.js, lib/moderation.js, lib/opentok.js, lib/signaling.js, package.json, sample/Archiving/index.js, sample/Archiving/public/js/host.js, sample/Archiving/public/js/participant.js, sample/HelloWorld/index.js, sample/HelloWorld/public/js/helloworld.js, sample/SipInterconnect/app.js, test/callbacks-test.js, test/helpers.js, test/moderation-test.js, test/opentok-test.js, test/signaling-test.js
Fixing linting errors
Run `npm run lint`
=> Linting error fixes

README.md, lib/broadcast.js, lib/client.js, lib/opentok.js, sample/Archiving/README.md, sample/Broadcast/README.md, sample/Broadcast/index.js, sample/Broadcast/package.json, sample/Broadcast/public/css/sample.css, sample/Broadcast/public/js/host.js, sample/Broadcast/public/js/index.js, sample/Broadcast/public/js/participant.js, sample/Broadcast/views/footer.ejs, sample/Broadcast/views/header.ejs, sample/Broadcast/views/host.ejs, sample/Broadcast/views/index.ejs, sample/Broadcast/views/participant.ejs, test/opentok-test.js
Adding methods to support [OpenTok live-streaming broadcasts](https://tokbox.com/developer/guides/broadcast/live-streaming/)
There are unit tests (`npm run test`) and there is a sample app in sample/Broadcast.
See issue #188.
=> Broadcast enhancements #188

README.md
=> minor broadcast readme changes

README.md, lib/opentok.js
Adding doc comment for the SIP `from` property and a sample of the `options` object to the README
N/A
N/A
=> add doc comment for from property and options to readme

lib/opentok.js
Editing the reference docs. OpenTok live streaming broadcasts now support RTMPS.
Build the docs.
None.
=> Docs change: support for RTMPS

README.md, lib/client.js, lib/opentok.js, test/opentok-test.js
Adds List Broadcasts API
```javascript
var options = {
sessionId: 'SESSIONID', // sessionId that you want to filter for (optional)
offset: '', // optional
count: '', // optional
}; 
opentok.listBroadcasts(options, function(error, broadcastList, totalCount) {
if (error) {
console.log('error', error);
} else {
console.log('broadcastList', broadcastList);
console.log('totalCount', totalCount);
} 
});
```
Internal tickets
=> [PENDING API REVIEW] add list broadcasts api

.travis.yml
Testing against Node 8, 9, 10
This PR will auto-run the tests in travis
=> Testing against Node 8, 9, 10

CODE_OF_CONDUCT.md, README.md, package.json
Includes:
- Updated README.md to include branding change image
- Updated README.md to define additional support options
- Added CODE_OF_CONDUCT.md
=> Updating repo to adhere to Vonage repo-standards

README.md, lib/client.js, lib/opentok.js, test/opentok-test.js
Adding support for new screen-sharing layout enhancements (to be available soon).
Modify the archive and broadcast sample apps to use the new `screenshareType` options for starting archives and broadcasts and for dynamically changing the archive and broadcast layouts.
=> New screenshareType layout API enhancements

README.md, lib/client.js, lib/opentok.js, package.json, test/opentok-test.js
=> v 2.12.0 - DTMF for SIP and SIP Video support

lib/opentok.js
Editing the docs for DTMF. The feature is no longer in beta.
N/A
N/A
=> Docs edit -- DTMF feature is no longer in beta

lib/archiving.js, lib/client.js, lib/opentok.js, test/opentok-test.js
This PR serves as the implementation of `forceMuteStream` and `forceMuteAll` methods.
https://jira.vonage.com/browse/DEVX-5443?src=confmacro
=> WIP[DEVX-5443] Add forceMuteStream and forceMuteAll

README.md, lib/opentok.js
Fixing some typos in the docs
N/A
N/A
=> Docs corrections

lib/client.js, lib/opentok.js, package.json, test/opentok-test.js
Low-Latency HLS Broadcast (Beta) [OPENTOK-45134](https://jira.vonage.com/browse/OPENTOK-45134)
Pause and Replay Broadcast - DVR (GA) [OPENTOK-45139](https://jira.vonage.com/browse/OPENTOK-45139)
=> add hls and dvr

lib/opentok.js
Clarifying the description of the signal() payload parameter.
N/A
N/A
=> Clarification of the signal() payload parameter

lib/archiving.js, package.json
add streammode to archiving post body
https://jira.vonage.com/browse/DEVX-6092
solves #266
=> add streammode to archiving post body

lib/archiving.js, spec/opentok_spec.js
=> patch response to 204

README.md
Fixing some typos in the readme.
N/A
N/A
=> Typo corrections

package-lock.json, package.json, test/opentok-test.js
This is updating the `jsonwebtoken` package to fix a critical vulnerability.
=> build: updating package

README.md, lib/opentok.js
Updating the name of the audio streamer to audio connector
=> refactor: renaming audio streamer

lib/opentok.js
Adding some missing docs
N/A
VIDECO-8469
=> Missing docs for addBroadcastStream() callback param

lib/broadcast.js, lib/opentok.js
Adding documentation for the `hlsStatus`, `maxBitRate` and `streams` parameters
=> doc: adding hls status, bitrate and sip stream documentation

lib/moderation.js
Correcting error strings for forceDisconnect() ArgumentError
N/A
N/A
=> Correct error strings for forceDisconnect() ArgumentError

lib/archiving.js, lib/opentok.js, sample/Broadcast/README.md
adds docs for 1080p
no test. only doc change
https://jira.vonage.com/browse/OPENTOK-45137
=> add 1080 in docs

test/archiving-test.js
Adds additional archiving tests to check errors
This is hard to do, as the API needs to throw a non-2xx error.
=> Added additional archiving tests

lib/api.js, lib/generateJwt.js, lib/opentok.js, package-lock.json, package.json, test/opentok-test.js, test/shim-test.js
Adding a shim to call the vonage Video API instead of OpenTok
Use your Vonage Application ID and Private key to make calls to create a video session
=> feat: added vonage video shim

lib/captions.js, package-lock.json, package.json, test/captions-test.js
Corrects the max-duration of transcriptions to 14400, which is the actual default
=> Transcription duration

lib/opentok.js
=> feat: added quantization parameter
